name: CI

on:
  push:
    branches: [ master ]  # Use 'main' se sua branch padrão for 'main'
  pull_request:
    branches: [ master ]  # Use 'main' se sua branch padrão for 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@latest  # Atualizado para a versão mais recente

    - name: Instalar dependências
      run: npm install

    - name: Executar testes
      run: npm test

    - name: Instalar sonar-scanner
      run: npm install -g sonar-scanner  # Tente instalar globalmente

    - name: Verificar instalação do sonar-scanner
      run: sonar-scanner --version  # Verifique se o sonar-scanner está instalado

    - name: Executar SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Certifique-se de que o token está adicionado nos Secrets
      run: |
        sonar-scanner \
          -Dsonar.projectKey=YOUR_PROJECT_KEY \  # Substitua pelo seu projectKey
          -Dsonar.organization=YOUR_ORGANIZATION \  # Substitua pela sua organization
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
