name: CI

on:
  push:
    branches: [ master ]  # Use 'main' se sua branch padrão for 'main'
  pull_request:
    branches: [ master ]  # Use 'main' se sua branch padrão for 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: npm install

    - name: Executar testes
      run: npm test

    - name: Instalar sonar-scanner
      run: npm install -g sonar-scanner

    - name: Verificar instalação do sonar-scanner
      run: sonar-scanner --version

    - name: Executar SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=YOUR_PROJECT_KEY \
          -Dsonar.organization=YOUR_ORGANIZATION \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
